### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by martinbagshaw** [martinbagshaw/ReactLogbook#48]
Adding tests is something I have neglected to do so far. Learning d3 basics, and becoming more competent at using React with hooks was a more important learning outcome at the time of project inception.

A list of points to cover, some of which will be new:

**Initial strategy**
- [ ] Unit tests of functions
- [ ] Unit tests of react components (render tests)
- [ ] Unit tests of react components (actions tests - click events etc.)
- [ ] Unit tests of d3 react components
- [ ] Integration tests. Try out Cypress, this would be a new thing to learn.

**Looking forward**
- [ ] How to test PWA components? (caching with service workers etc.)
